<?php

error_reporting(E_ALL);
ini_set('display_errors', 1);

// $Id$
/**
 * @file
 * Turn your drupal site into a link-shortening service
 */

/**
 * Implementation of hook_init().
 */
function shorty_init() {
  if (arg(0) && arg(0) == $_GET['q']) {
    $path = arg(0);
    $url = db_result(db_query("SELECT url FROM {shorty_links} WHERE token='%s'", $path));
    if ($url) {
      drupal_goto($url);
    }
  }  
}

/**
 * Implementation of hook_menu().
 */
function shorty_menu() {
  $items = array();
  $items['shorty'] = array(
    'title' => 'Shorten a URL',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('shorty_add_link'),
    'access arguments' => array('add shorty link'),
  );
  return $items;
}

function shorty_add_link() {
  $form['url'] = array (
    '#type' => 'textfield',
    '#title' => t('URL that you would like to shorten'),
    '#size' => 60,
    '#maxlength' => 128,    
  );
  $form['submit'] = array (
    '#type' => 'submit',
    '#value' => 'Submit', 
  );
  return $form;
}

function shorty_add_link_validate($form, &$form_state) {
  if (!valid_url($form_state['values']['url'], TRUE)) {
    form_set_error('url', 'Please enter a valid URL.');  
  }
}

function shorty_add_link_submit($form, &$form_state) {
  $url = check_url($form_state['values']['url']);
  $token = db_result(db_query("SELECT token FROM {shorty_links} WHERE url='%s'", $url));
  if ($token) {
    drupal_set_message(check_url($base_url . '/' . $token) . ' already points to ' . $url);
    return;     
  }
  global $base_url;
  $short = _shorty_get_token();

  $record = new stdClass(); 
  $record->token = $short; 
  $record->url = $url; 
  drupal_write_record('shorty_links', $record);
  drupal_set_message(check_url($base_url . '/' . $short) . ' now points to ' . $url);  
}

function _shorty_get_token() {
  $output = '';
  $max = variable_get('shorty_chars', 4);
  $type = variable_get('shorty_type', 'alphanum');
  for ($x=1; $x <= $max; $x++) {
    if ($type == 'alphanum') {
      $num = rand(1, 36);
      if ($num > 26) {
        $num = 21 + $num;
      }
      else {
        $num = 96 + $num;
      }
    }
    if ($type == 'alpha') {
      $num = chr(rand(97, 122));
    }
    $output .= chr($num);
  }
  // make sure $output don't exist in DB OR IN PATH TABLE!!
  return $output; 
}

/**
 * Implementation of hook_perm().
 */
function shorty_perm() {
  return array('add shorty link'); 
}